### ISSUE TITLE
VICREO-Listener : How to send Ctrl-Down key combination ?

### ISSUE THREAD

**Issue by LagaV** [bitfocus/companion-module-vicreo-hotkey#1]
**Describe the bug**
VICREO hotkey: Send stringmessage :

<KPRESS>ctrl <KPRESS> down<KRELEASE>down <KRELEASE>ctrl

doesn't deliver the result as expected (normal keyboard operation).

**To Reproduce**
VICREO hotkey: Send stringmessage : <KPRESS>ctrl <KPRESS> down<KRELEASE>down <KRELEASE>ctrl

entered as button

![image](https://user-images.githubusercontent.com/6940878/66467551-ea5c2200-ea84-11e9-915e-9a9f94f62179.png)

"Test action"

**Expected behavior**
Command executed as with "normal" keyboard operation.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1903

**Additional context**

**Comment by JeffreyDavidsz** [comment]
A string message is really a string message text, so you can type words....
You would have to use the other actions and in your case it's a combo of Ctrl and arrow down. Just down is not an option as I recall, check the help for that. Also remove the spaces in commands, the listener will remove trailing spaces but no spaces in front of your command

**Comment by LagaV** [comment]
Ok, got 

> A string message is really a string message text, so you can type words....
> You would have to use the other actions and in your case it's a combo of Ctrl and arrow down. Just down is not an option as I recall, check the help for that. Also remove the spaces in commands, the listener will remove trailing spaces but no spaces in front of your command

![image](https://user-images.githubusercontent.com/6940878/66551515-ecd38000-eb47-11e9-807c-afa59e688b35.png)

Ok, so now I'm at this:

VICREO hotkey: Combination -- 
Modifier: "Ctrl" & 
Key or modifier2: "<SPK>down" (same result with "down"

Same result! Not delivering the expected action.

**Comment by JeffreyDavidsz** [comment]
Only apply down as modifier no SPK

**Comment by JeffreyDavidsz** [comment]
You are on windows, do this 1st modifier "Command/Windows" and then "e".
That will open a explorer window on the machine you are controlling. If it doesn't check firewall, if it does make sure the focus is on the program you are trying to control.

**Comment by JeffreyDavidsz** [comment]
Ah ok so you are sending a emulated key press to a program that fetches keystrokes..... Some combinations might not work then. I'm going to close this issue, The module will send the command correctly and the way you are doing it now is also the right one. Check the AutoHotkey for a different fetching combination please
