### ISSUE TITLE
No Shell or Fileopen Commands working

### ISSUE THREAD

**Issue by vt-meister** [bitfocus/companion-module-vicreo-hotkey#10]
Hello,
first of all thank you for all the work and the help you offer here.
Unfortunately, I am really in despair. 
I'm trying to get anything but a plain text input (string message) to work, but the message in the log is always just "change to new syntax".
Neither "send shell command" nor "open file" works.
I hope you can help me.

tested versions 
2.09
2.10
Companion 2.1.2

Best Alex
![Companion](https://user-images.githubusercontent.com/55193422/107822231-0a3cdd80-6d7e-11eb-8f9a-df9819c852ff.png)
![VicreoLOG](https://user-images.githubusercontent.com/55193422/107822233-0ad57400-6d7e-11eb-84cd-d0649891f6cb.png)

**Comment by JeffreyDavidsz** [comment]
Put the right version in instance settings (click edit in Companion @the module
