### ISSUE TITLE
Vicreo TCP Error

### ISSUE THREAD

**Issue by timwowor** [bitfocus/companion-module-vicreo-hotkey#11]
I'm having issues with my Vicreo Listener Module. It can't open files from paths.

<img width="1686" alt="Screen Shot 2021-03-11 at 21 45 26" src="https://user-images.githubusercontent.com/62612303/110805055-557dd980-82b3-11eb-89b6-3b93e498407c.png">

**Comment by JeffreyDavidsz** [comment]
I cannot see the instance settings and the actions settings. Most likely you have spaces without \" around the command and if you do, most  likely you forgot to escape it like this \\"command\\"

**Comment by timwowor** [comment]
I'm trying to open file locally.

<img width="678" alt="Screen Shot 2021-03-12 at 00 18 34" src="https://user-images.githubusercontent.com/62612303/110827457-a9df8400-82c8-11eb-9a33-63fab8448c81.png">
<img width="730" alt="Screen Shot 2021-03-12 at 00 16 12" src="https://user-images.githubusercontent.com/62612303/110827487-b06dfb80-82c8-11eb-88db-6c2423e51367.png">

**Comment by timwowor** [comment]
Vicreo is receiving the commands, but just not opening the actual script file.

<img width="409" alt="Screen Shot 2021-03-12 at 00 22 05" src="https://user-images.githubusercontent.com/62612303/110827914-19ee0a00-82c9-11eb-835e-f45a74514cfc.png">

**Comment by JeffreyDavidsz** [comment]
Ah that looks like OSX. Try to use the full path. Click on the ? sign in Companion and scroll down how to do that

**Comment by timwowor** [comment]
I've already copied the full path and it's still not working :(

**Comment by JeffreyDavidsz** [comment]
Switch to open shell and paste te same I'm on windows can't check for you now, that should work

**Comment by JeffreyDavidsz** [comment]
Closing after no reply
