### ISSUE TITLE
Send shell command options require escape characters

### ISSUE THREAD

**Issue by rwarford** [bitfocus/companion-module-vicreo-hotkey#12]
Special characters such as the backslash (\) and quotation marks (") must be escaped with a backslash.  This is not intuitive.

For example, the following "Send shell command" action option WON'T work:

`start d:\users\roger\documents\hello.bat "Companion World"`

But it will work with escapes as shown here:

`start d:\\users\\roger\\documents\\hello.bat \"Companion World\"`

I can reproduce this behavior on Companion v2.1.2 with Vicreo Listener v2.0.9 running on Windows 10.

**Comment by JeffreyDavidsz** [comment]
This is pretty normal behaviour, making sure no one is trying to escape functions and inject some bad code in

**Comment by rwarford** [comment]
I think you misunderstand.  It looks to me like "Send shell command" is vulnerable to an injection attack because it appears to treat backslash as an escape character.  "\n" by itself seems to be treated as a single special character (presumably a carriage return) rather than two individual characters.

**Comment by JeffreyDavidsz** [comment]
Ah correct, that issue is resolved in 3.0.0 which I'm working on.
