### ISSUE TITLE
Can't get a .bat to execute with Open File

### ISSUE THREAD

**Issue by fakemaxwell** [bitfocus/companion-module-vicreo-hotkey#13]
On Vicreo 2.0.9, with Companion set to hotkey version > 2.0.5.  All other file types in the directory work, but can't get CMD to open with a .bat or with a shortcut.   On Windows 10.  Neither of the key actions in the picture work, I've tried all manner of different things to try and get it to go but no dice.  All the other functionality that I've tried to use in Vicreo is working.

![Screenshot 2021-03-25 230558](https://user-images.githubusercontent.com/59422275/112571573-b8e12e80-8dbe-11eb-9135-de000b4c1890.png)

**Comment by JeffreyDavidsz** [comment]
To me your command seems ok. You could try to put \\" around it

**Comment by fakemaxwell** [comment]
I tried a bunch of different ways of inputting the Open File string, no dice.  Was able to work around it with this shell command- `start cmd /k cd C:/video`

Still no dice on .bat files of any variety.  Otherwise everything else is working fine.

**Comment by JeffreyDavidsz** [comment]
In your log I can see SUCCESS, that looks strange might there be a path offset wrong in the bat file?

**Comment by JeffreyDavidsz** [comment]
Closing due to no reaction

**Comment by seanmcnally98** [comment]
If you want to run a batch script, create a Run Shell Path button under Internal, and put this inside:

`start "" cd "C:\Users\Owner\Path to File\batchscript.bat"`

The double quotes after start is important.  For whatever reason the first argument after the start command just names the command prompt window, the second argument actually tells it what to run.
