### ISSUE TITLE
"Open A File" command no longer working after Companion update 2.1.3

### ISSUE THREAD

**Issue by fakemaxwell** [bitfocus/companion-module-vicreo-hotkey#15]
All of my commands for opening files no longer work after updating to 2.1.3.  The key press commands and shell commands register on Vicreo Listener, but nothing appears for Open File.  Downgraded back to 2.1.2 and everything works again.  Tried both 2.0.9 and 2.1.0 for VL, on Windows 10.

**Comment by JeffreyDavidsz** [comment]
Van you show me the syntax you are using in Companion?

**Comment by fakemaxwell** [comment]
![Screenshot 2021-04-22 003319](https://user-images.githubusercontent.com/59422275/115656007-641fcd80-a302-11eb-9aef-ebf23c11d398.png)

It ends with ".lnk."  Have various commands to open shortcuts, exes, etc.  Tried all of them and none worked on 2.1.3.

**Comment by JeffreyDavidsz** [comment]
I've changed the help file as I recall (check the syntax there first) you might need a forward slash instead of backslash and you might need to put " around it because of the spaces in the names

**Comment by JeffreyDavidsz** [comment]
Yep it's the " missing. People had some problem with spaces slashes etc. So I've made it universal and added help. Now I've added an example preset. Put the " around the ones that don't work and you should be fine.

**Comment by fakemaxwell** [comment]
Got it, working now.  " " around paths fixed it. Thanks for the help!
