### ISSUE TITLE
Screenshot using 3 key Combination

### ISSUE THREAD

**Issue by DavidTNguyen** [bitfocus/companion-module-vicreo-hotkey#16]
I am trying to setup a button on perform screen capture on a Mac.  Normally, I use Command+Shift+4 for this task.  But the Companion button doesn't seem to respond as expected.  The cursor should have switched to a crosshair ready for screen capture upon button pressed, but nothing happened.  Am I configuring it correctly?
![2021-04-23 14 57 32](https://user-images.githubusercontent.com/11265859/115923879-8faad100-a444-11eb-934f-36fa04288c4e.gif)

**Comment by JeffreyDavidsz** [comment]
I would say so, but no mac available at the moment. Did you try other combinations to see if all rights are set?

**Comment by DavidTNguyen** [comment]
I was able to setup a lot of three key combinations to manage Zoom call. It's only this specific combo that refuse to work.

**Comment by JeffreyDavidsz** [comment]
Sometimes an other applications is catching some commands, does it work when you open a finder and then use the tri function?

**Comment by JeffreyDavidsz** [comment]
Closing after no reply
