### ISSUE TITLE
Key commands not executing on Windows 10

### ISSUE THREAD

**Issue by kd8ssq** [bitfocus/companion-module-vicreo-hotkey#2]
I'm trying to set up the Vicreo listener on both my Windows and Mac machines in order to set up a companion button to lock the machines.  I've programmed in the proper commands for both and while the Mac locks as it should, nothing happens on the Windows machine.  I'm using the key commands Windows + L to lock the computer.  When I turn on the notifications for the listener, I can see the command is received (except it says it received the "cmd" + "l"; I'm assuming because the Windows and mac Command key are the same).  I've put a 5000 ms delay between the execution of the Windows and Mac commands with the Windows command being last (since that's where Companion is located).  

Any ideas?

Thanks,

Adam

**Comment by JeffreyDavidsz** [comment]
Did you do a key combo? Or a press release? Can you show your companion settings?

**Comment by kd8ssq** [comment]
Jeff,

Here you go.

![image](https://user-images.githubusercontent.com/6402523/67511009-073b4c80-f664-11e9-9018-32062423c3d3.png)

**Comment by JeffreyDavidsz** [comment]
I've tested it. At my laptop windows key + L also doesn't work. Tested the windows key + E, works tested Ctrl + l works also. I think this is a blocked combination on windows. There are some cases where some keyboard emulation tricks don't work. I'll keep this issue open to collect data for more combinations

**Comment by kd8ssq** [comment]
Bummer.  Thanks for testing.

**Comment by kd8ssq** [comment]
In case anyone else is interested, I figured out a workaround.  I just told
the listener to execute a local file and I wrote a batch file to trigger
the lock command for windows.

Adam

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
