### ISSUE TITLE
Arrow command not working in ver.3.0.3

### ISSUE THREAD

**Issue by pilgrims1** [bitfocus/companion-module-vicreo-hotkey#20]
When I using it, it works well other special keys like "TAB"
But not working in ARROW keys.
This is why ???

Raspberry Pi 4B
companion 2.2.0 (2.2.0-509a6a41-3498) This build is experimental
Windows 10 latest updated.

Finally I'm succeed with your VICREO-HOTKEY ver. 2.1.0 for windows.

And your download link which web page sent not working in Chrome Browser.
So I had to open that link on Edge browser.

**Comment by JeffreyDavidsz** [comment]
Try to use the left/right arrow in a different application, to see if it works there (I've tested it and it works).
But there was a fix on special keys coming from companion (companion-2.2.0-b806279e-3501).
{"key":"left","type":"pressSpecial","modifiers":[],"password":"d41d8cd98f00b204e9800998ecf8427e"} should work
{"key":"left","type":"press","modifiers":[],"password":"d41d8cd98f00b204e9800998ecf8427e"} in your log, means you need to update to the latest Companion for the fix

**Comment by pilgrims1** [comment]
Thanks Jeffrey....
In my experience,
every case failed with ver. 3.0.3 VICREO LISTENER.
1. Raspberry Pi 4B
companion 2.2.0 (2.2.0-509a6a41-3498) This build is experimental
Windows 10 latest updated.
2. Windows 10 note book edit Ui
companion 2.1.2 windows version
Windows 10 latest updated.

In my case.... two environments both failed to transfer "Arrow Left, Right"

**Comment by JeffreyDavidsz** [comment]
You probably need latest build of companion, see my earlier note on the build number.
Send my the listener log to be sure

**Comment by JeffreyDavidsz** [comment]
close due no response
