### ISSUE TITLE
Using Beta Companion with a Pi4 - Vicreo Listener not sending commands

### ISSUE THREAD

**Issue by franklyray** [bitfocus/companion-module-vicreo-hotkey#21]
Just switched - 2.2.0 (2.2.0-af93d1a0-3464) This build is experimental to a Raspberry Pi4. Fully functioning with ATEM but not with simple commands to connected computers. See photos. 

Also working with VLC running videos on both computers

![Vicreo screen](https://user-images.githubusercontent.com/4950599/130268987-4bdc9e45-c602-41d0-8fb7-ff27ad7c86b7.jpg)

![CMD + TAB](https://user-images.githubusercontent.com/4950599/130269405-a9af979d-a7a5-4f7e-bbf0-342e4afcb48e.jpg)

Please advise. Thanks

**Comment by JeffreyDavidsz** [comment]
Which version of the listener and did you set that in the companion instance?

**Comment by franklyray** [comment]
3.03

**Comment by JeffreyDavidsz** [comment]
And did you select > 3.0.0?

**Comment by franklyray** [comment]
I imported the previous install (on my PC) with hotkey version ?? (3.0.0)
came up automatically.

Only drop-down choices were below 2.0 or above 2.05.

Please advise.

**Comment by JeffreyDavidsz** [comment]
If you cannot choose > 3.0.0 somehow you have the wrong beta version. Download the latest and try again?

**Comment by JeffreyDavidsz** [comment]
closing due no response
