### ISSUE TITLE
Key Press not working on Windows 10

### ISSUE THREAD

**Issue by glenn-fredrx** [bitfocus/companion-module-vicreo-hotkey#22]
I am using Bitfocus Companion v2.1.3 and Vicreo v3.0.3.  I have configured it with IP, port and version.

![image](https://user-images.githubusercontent.com/70785189/130364790-1f99e0c8-e5dc-4e0e-bf45-5219dc5ab4ef.png)

I know it can connect, as I am able to use commands like Send stringmessage and Send shell command.  When trying to use the Combination, it appears not to be sending the correct command.  I am trying to send the Alt+a command.  In the Vicreo log I see this:
12:46:30 When you want to use modifiers, use the combination or trio syntax please
12:46:30 received: {"key":"a","type":"press","modifiers":["alt"]}

It appears it should be setting the type to combination not press.

If I use nc and send the correct command:  { "key":"a", "type":"combination", "modifiers":["alt"] }
it will run as expected.

**Comment by glenn-fredrx** [comment]
I was nosing around and saw on your FAQ that I needed a beta release of Bitfocus later than Aug 10th.  I found a release and installed that.  It is now working as expected.

Thanks for this app, it is great.  Appreciate all your work on this.

**Comment by JeffreyDavidsz** [comment]
Good that you got it working! Feel free to donate a little bit if you use it a lot ;-)
