### ISSUE TITLE
Enter Key Press doesn’t seem to be working on Mac

### ISSUE THREAD

**Issue by kd8ssq** [bitfocus/companion-module-vicreo-hotkey#23]
Companion: 2.2.0 (2.2.0-b80627e-3501)
Vicreo: 3.0.3
Mac: Big Sur 11.3.1

I can see the Enter command being passed to the Mac, but it doesn’t seem to be triggering.  I normally use it to close a dialog, but in order to test that it was being sent, I opened up Notepad and tried to see if it would add a new line and it doesn’t.  

Received: {“key” : ”Enter” , ”type” : “down”, “modifiers” : [], “password” : “password”}

I know in the past I’ve seen issues where “case” has mattered in companion, so I tried “Enter” and “enter” and neither actually triggered the enter key on the Mac.  

Thanks

Adam De Lay

**Comment by JeffreyDavidsz** [comment]
Type=down are you sending an up also?

**Comment by kd8ssq** [comment]
No, I’m just trying to send a single key press like I was before I upgraded
to 3.0.3.

**Comment by JeffreyDavidsz** [comment]
Remove the action and put in a new one, just down doesn't work, might be that some programs respond to it though

**Comment by JeffreyDavidsz** [comment]
Did it work for you? If so please close the issue

**Comment by kd8ssq** [comment]
What action should I be using if I want to simulate an “Enter” keypress?

**Comment by JeffreyDavidsz** [comment]
From companion you can choose for example special key

**Comment by JeffreyDavidsz** [comment]
Did it work for you?

**Comment by kd8ssq** [comment]
Sorry, been a busy week.

Yes it worked.  In the past before I upgraded I just had a "keypress" in
place and it worked fine.  Now it's working again with the "special key".

Thanks for everything, and keep up the good work!

Adam
