### ISSUE TITLE
Issue With MacOS StringMessage

### ISSUE THREAD

**Issue by sholight** [bitfocus/companion-module-vicreo-hotkey#25]
I'm working on building shortcut commands for Vectorworks and a number of the menu commands require four buttons (e.g. "H,Cmd,Alt,Shift". Since I can't do four button combos using "Send KeyPress To MacOS Process" I thought I'd try doing "Send StringMessage" using the follow syntax:
     { "key":"0x04","type":"processOSX","processName":"Vectorworks 2022","modifiers":["shift”,”alt”,”command”] }

Sadly it doesn't seem to work. I'm not even using it passed to the listener. Tried with and without including the password string but no luck.

What am I missing?

**Comment by minkpan** [comment]
I have a workaround that I previously programmed with pbcopy and pbpaste, but string messages don't seem to be working on my new M1 Max Mac. The log shows `13:38:19 Action: ok - typing
13:38:19 received: {"type":"string","msg":"Hello","password":"d41d8cd98f00b204e9800998ecf8427e"}
` but nothing happens in the empty TextEdit window I'm using to test.

**Comment by JeffreyDavidsz** [comment]
Haven't test it on a M1 yet. But did you gave permission for Accessibility and Automation?

**Comment by minkpan** [comment]
All permissions have been given. Other commands (keystrokes, open file, shell command) all work. Only sending strings seems to net me nothing.

**Comment by JeffreyDavidsz** [comment]
Did you got the chance to test it?

**Comment by JeffreyDavidsz** [comment]
close due to no response

**Comment by minkpan** [comment]
So sorry! Work picked up and I never got back to the project I was working on. I've just done some testing with Vicreo version 5, and it seems to be working well - the only thing that it still seems to have trouble with is maintaining case sensitivity (at least when I use TextEdit as a testing site), but that isn't too big a deal for what I'm trying to accomplish.

**Comment by JeffreyDavidsz** [comment]
I think, that's something I need to change. Everything is lower case now

**Comment by JeffreyDavidsz** [comment]
Just for reference the upper/lowercase is fixed for windows and OSX (version 9.4.0)
