### ISSUE TITLE
Only Shell Commands are working

### ISSUE THREAD

**Issue by N8866U** [bitfocus/companion-module-vicreo-hotkey#26]
10:34:42 When you want to use modifiers, use the combination or trio syntax please
This is the response to any command other than a shell command or a string message. String messages return "Action: ok - typing", but nothing gets typed. Only the shell commands get sent to the computer. Does anyone know how to fix this?

**Comment by Pippin1926** [comment]
> I think you are on the wrong version of companion. Are you using 3.0.3 of the listener? You should have a beta then

Using 3.0.3 and the latest beta

**Comment by JeffreyDavidsz** [comment]
@Pippin1926 for the hot single key theres an error indeed! I fixed this and push a new version of Companion Beta. Work arround is to send with general TCP {"key":"c","type":"press","password":"d41d8cd98f00b204e9800998ecf8427e"}
