### ISSUE TITLE
Missing Function Keys F13 - F24

### ISSUE THREAD

**Issue by norges** [bitfocus/companion-module-vicreo-hotkey#27]
I would ask to add Function keys above F12, to be able to use them in viecro

**Comment by JeffreyDavidsz** [comment]
Those should work, version of companion and vicreo?

**Comment by norges** [comment]
Viecro 2.1.0 and companion 2.0, in the dropdown only F1-F12 can be select
![Screenshot 2021-10-05 at 15 49 39](https://user-images.githubusercontent.com/2143057/136036266-6b09899a-5a3b-4cc5-b9f5-d1fb9fcba90e.png)
ed

**Comment by JeffreyDavidsz** [comment]
This is fixed in newer releases. The listener supports it but the companion needs a update

**Comment by norges** [comment]
oh thank you I close here then
