### ISSUE TITLE
\ and ` keys

### ISSUE THREAD

**Issue by dwest24sc** [bitfocus/companion-module-vicreo-hotkey#30]
Hello,
I have a need for the \ key any chance it may become an accepted key? Or a special key?  

Also, it seems the program takes the ` key but maybe doesn't pass it on to the computer.  Any chance that key be be supported too?

Thanks

**Comment by JeffreyDavidsz** [comment]
\ (backslash) will be in version 4.0.11 just added it

**Comment by dwest24sc** [comment]
Wonderful!  Thank you.

David West
W6DMW

________________________________
