### ISSUE TITLE
ALT on Ubuntu

### ISSUE THREAD

**Issue by alex-p75** [bitfocus/companion-module-vicreo-hotkey#31]
Hi,
I am on Ubuntu 20.04, with Bitfocus companion version 2.2.0-a8984e8e-3544 and vicreo listner 3.0.3. 
If I choose hotkey combination as modifier I can choose Option/alt or right alt
With both, every combination with alt modifier doesn't work.
As keyboard disposition I have US, so there is not difference between right alt and left alt.
For home folder for example, the default shortcut is alt+h, in app log i see
`9:36:07 received: {"key":"h","type":"combination","modifiers":["alt"],"password":"d41d8cd98f00b204e9800998ecf8427e"}
9:18:05 connected
9:17:59 Found IPv4 address: 192.168.26.1
9:17:59 Found IPv4 address: 192.168.151.1
9:17:59 Found IPv4 address: 192.168.200.140`

but nothing appened.

Thank you

**Comment by JeffreyDavidsz** [comment]
Can you confirm other modifiers do work?

**Comment by alex-p75** [comment]
Yes, I have tried various combinations but only if the alt key is involved it does not work

**Comment by alex-p75** [comment]
Hi.
I try to uninstall and reinstall latest bitfocus and vicreo but now any modifiers doesn't work (on ubuntu)

**Comment by JeffreyDavidsz** [comment]
Did you select the right version in the instance settings (in companion)

**Comment by alex-p75** [comment]
yes, if I don't use modifier it works

**Comment by alex-p75** [comment]
This is my conf
![Schermata da 2021-12-27 13-23-55](https://user-images.githubusercontent.com/79105192/147471655-45170b86-932c-4285-98e3-ae88763ed604.png)
![Schermata da 2021-12-27 13-25-03](https://user-images.githubusercontent.com/79105192/147471665-d2f3ebf5-2b8e-452a-8f19-256a0231b5d3.png)
![Schermata da 2021-12-27 13-26-21](https://user-images.githubusercontent.com/79105192/147471697-86d878d3-88a3-4b18-984d-018ecc387210.png)

and this is the log

`13:24:28 received: {"key":"H","type":"trio","modifiers":["shift","control"],"password":"6ebe76c9fb411be97b3b0d48b791a7c9"}
11:26:03 connected
11:25:58 Found IPv4 address: 192.168.200.201
11:25:58 Found IPv4 address: 192.168.200.140
`

**Comment by JeffreyDavidsz** [comment]
You said only when alt is involved it doesn't work, but in the example above there is no alt. I think I know where the problem is coming from (there is a check for darwin (OSX) and the rest is a windows function. That's why I'm a bit confused that other functions work

**Comment by alex-p75** [comment]
Sorry for my poor english :)

Last week I try to make a clean reinstall of bitfocus companion and vicreo listner and after reinstall every modifier key (alt, ctrl, super) doesn't work

**Comment by JeffreyDavidsz** [comment]
Hi @alex-p75 there is a new version of the listener with support for linux but not tested yet version 4.0.9 at the moment. I need to test it myself on ubuntu. But you can try the combination key and single key. You'll need a license for the other actions.

**Comment by JeffreyDavidsz** [comment]
closing do to no response
