### ISSUE TITLE
'Send KeyPress To MacOS Process' not working

### ISSUE THREAD

**Issue by tacvideo** [bitfocus/companion-module-vicreo-hotkey#32]
I can see in VICREO-Listener logs that it got the instruction/communication, the application that I reference get "focus", but no key presses happen. I've tried CMD+0 (for ProPresenter) and more simplistic just plain ANSI_A to TextEdit.

 VICREO-Listener has permissions to control "System Events"...

What am I missing?

MacOSX 11.6

**Comment by JeffreyDavidsz** [comment]
Screenshot of the log of VICREO-Listener?

**Comment by tacvideo** [comment]
Here you go...
<img width="412" alt="Screen Shot 2021-12-17 at 1 34 29 PM" src="https://user-images.githubusercontent.com/73620763/146604852-dd03d680-9c39-49b7-9522-9dd662a4d35a.png">
and the text from within the window...
13:47:44 received: {"key":"0x24","type":"processOSX","processName":"TextEdit","modifiers":[]}
13:47:44 received: {"key":"0x09","type":"processOSX","processName":"TextEdit","modifiers":["command"]}
13:47:41 received: {"key":"0x24","type":"processOSX","processName":"TextEdit","modifiers":[]}
13:47:41 received: {"key":"0x09","type":"processOSX","processName":"TextEdit","modifiers":["command"]}
13:43:28 received: {"key":"0x52","type":"processOSX","processName":"ProPresenter 6","modifiers":["command"]}
13:40:57 received: {"key":"0x09","type":"processOSX","processName":"TextEdit","modifiers":["command"]}
13:40:23 received: {"key":"0x09","type":"processOSX","processName":"TextEdit","modifiers":["command"]}
13:38:54 received: {"key":"0x08","type":"processOSX","processName":"TextEdit","modifiers":[]}
13:38:25 received: {"key":"0x0B","type":"processOSX","processName":"TextEdit","modifiers":[]}
13:37:25 received: {"key":"0x00","type":"processOSX","processName":"TextEdit","modifiers":[]}
13:37:20 received: {"key":"0x00","type":"processOSX","processName":"TextEdit","modifiers":[]}
13:33:54 connected
13:33:53 Found IPv4 address: 10.1.40.40

**Comment by JeffreyDavidsz** [comment]
Did you try a normal (single) keypress? Could still be a rights thing.

**Comment by tacvideo** [comment]
Yes, tried ANSI_A to ProPresenter, and to TextEdit. 

Probably is a rights thing, but the only popup I saw about rights was for "Events" which it has rights to. saw somewhere that it uses AppleScript, but I have no idea how to check that...

**Comment by tacvideo** [comment]
Also, as I said before, the App I send the command to does "get focus" - I purposely switched to a different App before I sent the command, it' just the actual keystroke that gets ignored

**Comment by JeffreyDavidsz** [comment]
Normal single is a different action. So don't use send key to process. Just to test

**Comment by tacvideo** [comment]
I don't have "Normal single" in Companion's "VICREO hotkey", but "Hot(single)key" doesn't do anything either

**Comment by JeffreyDavidsz** [comment]
Thats the one, if that doesn't work, you probably have a rights issue. I'm not a mac user but under accessibility you should find some options?

**Comment by tacvideo** [comment]
Good news, figured out the problem. VICREO must selected in 2 places (I only had it selected under Automation / "System Events")
![image](https://user-images.githubusercontent.com/73620763/147617195-b45ea86b-0611-49bf-a51c-2acbc80b2994.png)

was missing this one...
![image](https://user-images.githubusercontent.com/73620763/147617143-62b41181-4a30-47f6-b8f8-6caa7c1a941a.png)

**Comment by JeffreyDavidsz** [comment]
Good, thanks for the screenshots
