### ISSUE TITLE
Quad Key Combos

### ISSUE THREAD

**Issue by Wes-Koetje** [bitfocus/companion-module-vicreo-hotkey#34]
How can I send a Quad Key combo like Google Sheets uses to run a Macro?
     ⌘ + Option + Shift + 7
Looks like single, double and trio are all done with ease, but I could use a quad. 
Any idea?

**Comment by JeffreyDavidsz** [comment]
I think you should do it by hand, copy paste a 3 trio command from the log into a generic-tcp module on port 10000. Then add the extra 4th modifier
