### ISSUE TITLE
Start with no UI

### ISSUE THREAD

**Issue by drakz-AU** [bitfocus/companion-module-vicreo-hotkey#35]
Hi,

I have Vicreo included in my startup apps, this means that the UI shows up ever time I log in.

Would it be possible to have the option to start minimised to tray / no UI?

Thanks

**Comment by JeffreyDavidsz** [comment]
I believe that's already in there? Depends on your version but if I remember correctly I put it in the tray, start minimize or something. Let me know if you can find it .

**Comment by drakz-AU** [comment]
Now that you've told me that it's there I've found it.
Need to right-click the system tray and the option is in the menu there,
but only in Version 3.
I was looking for a toggle in the UI of version 2 (which I'm using since
I'm not using Bitfocus Companion beta)
No wonder I couldn't find it. I'll have to look at switching to the beta
version.
Thanks for the reply.

**Comment by JeffreyDavidsz** [comment]
Check!
