### ISSUE TITLE
VICREO module doesn't seem to re-establish connection with VICREO listener after windows resumes from sleep

### ISSUE THREAD

**Issue by lvnilesh** [bitfocus/companion-module-vicreo-hotkey#39]
Not sure whether the issue is with the module or the listener.

Linking to the related issue.

https://github.com/JeffreyDavidsz/VICREO-Listener-ISSUES/issues/4

Appreciate your help with a resolution. 

Thanks for VICREO and COMPANION.

**Comment by JeffreyDavidsz** [comment]
I've changed some code but it seems that its a global Companion thing, closing this. If there are any issues let for you please feel free to address them
