### ISSUE TITLE
[BUG] Vicreo Hotkey - "Send stringmessage"

### ISSUE THREAD

**Issue by IanTGreenwood** [bitfocus/companion-module-vicreo-hotkey#4]
Using latest (2.0.0-26851f7-2021) and Vicreo 1.4.0 (MacOS).

When using "Send stringmessage" action.  Any capital letters seem to be interpreted as a lowercase 'a'.

**Comment by JeffreyDavidsz** [comment]
In the newer version its typing on the key's so no capitals at the moment
