### ISSUE TITLE
run at startup and auto minimize

### ISSUE THREAD

**Issue by Mohsen89M** [bitfocus/companion-module-vicreo-hotkey#40]
Hi,

im using version 2.1.0

can you add feature to auto minimize the app ?

I already added the app on startup but it when i run my pc it show up and that bother me lol

I suggest to add these feature in the app its easy i think

thanks

**Comment by istnv** [comment]
Look for the small checkbox on the starting window:
 `[] Start minimized`

**Comment by JeffreyDavidsz** [comment]
As I recall I've added it after that version, but you would need to use a beta of Companion to

**Comment by Mohsen89M** [comment]
> 
what is the version ? because i only see version 2.0.8 here !

**Comment by JeffreyDavidsz** [comment]
You should go to vicreo-listener.com for download. I have no idea where you get the 2.0.8 version?

**Comment by Mohsen89M** [comment]
the feature you take about its only in version 3.0.3

can you please add it in version 2.1.0 !

**Comment by JeffreyDavidsz** [comment]
@Mohsen89M sorry, each addition or bugfix will be a new version. Some changes are that big that they are not backward compatible. That being said it perfectly fine to use a beta from Companion. Just test it for yourself before you use it in live production.
