### ISSUE TITLE
Issue with file paths that have spaces

### ISSUE THREAD

**Issue by tyler351** [bitfocus/companion-module-vicreo-hotkey#41]
I'm trying to open a file using the built-in open in the vicreo module. The issue I'm having is the file path has spaces in it and the vicreo app seems to not like the spaces. I've tried a few different thing to see if it helped, such as, formatting it the way that macos terminal would with backslashs in between the words where the spaces are. (/Applecations/Studio\ One\ 5.app). I tried with quotes around everything and with out.
I even tried running a shell command but that didnt seem to work either. 

The output in the vicreo app is the following:
```
:04:52 error: Command failed: open /Applications/Studio One 5.app
The files /Applications/Studio, /One, and /5.app do not exist.

```
What am I missing?

**Comment by JeffreyDavidsz** [comment]
Version?

**Comment by tyler351** [comment]
Whoops. Meant to put that in here. 

Companion version is 2.4.1 i believe. 
Vicreo listener version is 3.0.3

**Comment by JeffreyDavidsz** [comment]
I think I can see where the issue is but need to test on a mac. could you try a shell action?
open "/Applications/Studio One 5.app"
So with the " around the path and file

**Comment by JeffreyDavidsz** [comment]
Error message if any is ok

**Comment by JeffreyDavidsz** [comment]
Did you try it?

**Comment by tyler351** [comment]
I'm so sorry. I haven't had a chance to try it yet. I can try it first thing tomorrow.

**Comment by tyler351** [comment]
So I ended up having to rebuild the setup that I was using this instance on… the issue seems fixed in the later version of vicreo in conjunction with the latest version of companion.

**Comment by JeffreyDavidsz** [comment]
Check
