### ISSUE TITLE
feature request: 4 buttons

### ISSUE THREAD

**Issue by mctober** [bitfocus/companion-module-vicreo-hotkey#43]
Hey,

Is it possible to add a function for four buttons (three modifiers+key)? I use Vicreo a lot with Vectorworks which has some functions that require four buttons.

Keep up the good work, thanks!

cheers,

Mark.

**Comment by iddqdosc** [comment]
While at it, is it possible to also include the WIN key as a modifier? Thank you.

**Comment by iddqdosc** [comment]
That would be highly appreciated! Thank you.

**Comment by JeffreyDavidsz** [comment]
I've added this in Companion, the listener will be upgraded to version 4.0.3
