### ISSUE TITLE
Issue with Mac Keyboard Shortcuts (Function Keys)

### ISSUE THREAD

**Issue by CSFtech502** [bitfocus/companion-module-vicreo-hotkey#47]
**Describe the bug**

**Version**
Which version of the listener and which version of companion

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System (please complete the following information):**

- Companion Version [e.g. 2.2.0 (70d5207-2717)]
- vMix version [e.g. v23]

**Additional context**

**Comment by CSFtech502** [comment]
Hi there. Not sure if this is a bug or just user error.  I'm running v2.2.0 of Companion and v3.0.3 of Listener.  

I'm having an issue using a combination hotkey with modifier Command and special key F1.  My listening device is a Mac, and those keystrokes should mirror the display, but it doesn't work.  

Upon further investigating with single special keys, it seems that Listener is using keyboard shortcuts, but not the native Fn keys.  So the Fn keys for muting volume and playing/pausing don't work either. 

When I did a special hotkey with button F11 it did the "Show Desktop" shortcut.  I found this in the system preferences for keyboard shortcuts.  

So what I'm asking is if there's a way for Listener to use the native Fn keys, if that makes sense, so that Command-F1 mirrors display.  Or in the previous example with F11, so a special key button with F11 would turn down volume, not show desktop. 

Hope this makes sense.  Thanks!

**Comment by JeffreyDavidsz** [comment]
It does make sense, i'm a windows user myself, but I'll take a look at it

**Comment by JeffreyDavidsz** [comment]
Could you try the send to process action? Leave the process name empty and use the F1...12 key as virtual keycode and the fn for modifier, I probably need to upgrade the companion module also. But it might work directly. Leave the second modifier as is.

**Comment by JeffreyDavidsz** [comment]
I forgot the fn key isn't a key and not exposed to the driver, so in combination with a key it will just show a new key. For mac its a bit testing, but I think I have the solution. After testing I'll update the listener.

**Comment by ready1take1** [comment]
did this ever get resolved? I am on a pro account version 8.0.6 on a mac and can't get the "fn/globe" button to work.

**Comment by JeffreyDavidsz** [comment]
There is no "resolve". The fn keys are shortcuts to get more keys on a keyboard. Not all functions are there. The volume etc is there for example. The globe function does a webbrowser? For now do a file open with the browser als a link. I'll see if I can find the keycodes for that

**Comment by ready1take1** [comment]
Hmmm so I am trying to fire off a keyboard shortcut to go fullscreen in Preview. And the keyboard shortcut for that is fn(the globe icon)+F. I attached what it looks like. 
<img width="255" alt="Screenshot 2024-05-16 at 10 05 53 AM" src="https://github.com/bitfocus/companion-module-vicreo-hotkey/assets/155566990/a176d062-9e43-4c6c-ad70-7ef22ccbbce0">

**Comment by JeffreyDavidsz** [comment]
Ah ok thats clear. For OSX I found a way to use the fn key. its released in 8.1.5 of the listener now will be on the website shortly
