### ISSUE TITLE
Certain hotkeys not functioning properly (revised)

### ISSUE THREAD

**Issue by BrianBATL** [bitfocus/companion-module-vicreo-hotkey#48]
Per your request I'm creating a new bug report.

There seems to be some confusion with my previous bug report where I explain that I used the "command" modifier/special key even though I'm on a PC using Windows.

It's because you don't have a "windows" key modifier.  And "command" appears to be mapped to the "windows" key and seemingly doing the same job.

Now that all said, I need a trio key that takes the active window and snaps/screen shifts it to an adjacent monitor.

At some version in the past, I had a three-key button of "command+shift+[arrow key]" (ie. left or right) that use to work just fine.  But now it does not.

The Vicreo Listener log box shows what looks like a correct function received "Key: left, Type: trio, Modifiers: command, shift", but it does not work.  I've tried "Key: Arrow Left, Type: trio, Modifiers: command, shift", using your Special Key syntax too, but still no luck.

Key: left or right, or Special Key: Arrow left or Arrow right, by themselves on either Hotkey Special Key, Hot(single)key, or the single Key Press, function properly.  They will move a cursor left or right just fine in Notepad or even here in this edit box, for instance.

But when in a Combination or Trio, they do not work.

In Windows, "windows key+shift+[direction arrow key]" is supposed to shift the active screen to an adjacent monitor.  But Vicreo no longer does this in any capacity that I can find.  It SHOULD work on your trio function, and it use to work in older versions, but something changed and now it doesn't.

As mentioned previously, I can't quite tell if the breakdown in the function is coming from the Shift key not responding as a modifier, or the arrow keys not responding as Special Keys/non-modifiers, or the Command key (Windows key) maybe not responding as a modifier, or there being some malfunction in processessing certain special keys/regular keys after certain modifiers in a Combination or Trio sequence.

I am using the latest version of Companion (2.2.0+4038) and Vicreo 3.0.3, and have the >3.0.0 setting in the config.

I hope you get time to look at this soon.  I'm shooting videos currently and having to program G-keys on my keyboard for this when I'd really love to do it on my Stream Deck with the rest of my buttons.

**Comment by JeffreyDavidsz** [comment]
Hi @BrianBATL I've updated the Listener to version 4.0.2 You can download it from the site. Be aware you will need a license to use all functionality (for example trio function). Send me an email (info@vicreo.eu) With your Name and email, and I'll send you a license key. This because of your patients and help to make the Listener better.

**Comment by JeffreyDavidsz** [comment]
Hi @BrianBATL Did you got it working? I could test it with Ctrl + Shift + Left

**Comment by BrianBATL** [comment]
Sorry for the delay, I got busy the past couple days at work.

YES!  4.0.8 works.  The Shift key is responding in the 2nd modifier slot now.  So "Command+Shift+[arrow key]" finally does the active screen shift to an adjacent monitor.

Thank you so much for fixing this.

**Comment by JeffreyDavidsz** [comment]
No problem, I'll close this, let me know if you need any help with other stuff
