### ISSUE TITLE
VICREO hotkey: special key ctrl + F* doesn't work[BUG]

### ISSUE THREAD

**Issue by Mohsen89M** [bitfocus/companion-module-vicreo-hotkey#49]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

hello,

i have dual pc using stream deck on the second pc tp send command to main pc
trying to send commands to manage discord in main pc
I used Ctrl + F9 to toggle mute discord 
and Ctrl + F10 to toggle deafen discord

now those buttons doesn't match together when i updated to version 2.2, i tried also tap or shift but nothing work

when i was using the old version it was fine. if i use any other key it also work fine but i want to use ctrl/shift/ with F*

### Environment (please complete the following information)

```markdown
- OS: w10
- Browser: opera gx
- Companion Version: 2.2.0 (2.2.0+3998-ccea40c7)
```

**Comment by Mohsen89M** [comment]
thanes for the fast replay

do you mean Press actions VICREO hotkey: Combination ? if yes i tried it and its working but i don't know how to yse F* or numpad on (Special) Key !

and all buttons show up in the log.

**Comment by JeffreyDavidsz** [comment]
With combination you can use Ctrl as modifier and type F7 for key. Numpad is also possible out of my head it is numpad_3 for example but I would need to check that

**Comment by Mohsen89M** [comment]
I figured it out that i should select the special keys in Combination then press it in the keybinds in discord that the best why to let it work fine lol sorry if i disrupted you

**Comment by JeffreyDavidsz** [comment]
No problem, there is an issue with certain keys in a combination/trio/quartet. I've just fixed that. new version (4.0.8) will be up in a few
