### ISSUE TITLE
I can't get even single keypress to work

### ISSUE THREAD

**Issue by mac25rice** [bitfocus/companion-module-vicreo-hotkey#50]
**Describe the bug**
I'm trying to control PowerPoint
Vicreo log is registering the keypress -- received: {"key":"n","type":"down","modifiers":[]} -- but nothing is happening in powerpoint or any other application. However, if I press "n" on the keyboard, it goes to the next slide. 
I tried "hot(single)key", "key press" and others but nothing seems to work. 

**Version**
Companion 2.1.4
Vicreo 4.0.6

**To Reproduce**
Steps to reproduce the behaviour:

1. In Companion set a regular button and add any Vicreo action that may let you go to the next slide in PowerPoint (like "N", "Spacebar", "right arrow", etc) when pressing that Stream Deck button
2. Open PowerPoint, set it to presentation mode and press the Stream Deck button. The slide doesn't change. 
3. Press "N" or "Spacebar" or "right arrow" in the keyboard and the slide changes. 
4. Check the Vicreo logs and it registered the keypress but slide did not change.

**Expected behaviour**
To be able to go to the next slide in PowerPoint when pressing a button in Stream Deck. 

**Screenshots**
Attaching multiple
![Screen Shot 2022-03-31 at 11 57 00 AM](https://user-images.githubusercontent.com/102754207/161110450-1895468b-7bdd-499e-8515-b477fe365cda.png)
![Screen Shot 2022-03-31 at 11 58 45 AM](https://user-images.githubusercontent.com/102754207/161110451-f0a50a9f-2393-4380-9e70-29461f63d683.png)
![Screen Shot 2022-03-31 at 11 59 01 AM](https://user-images.githubusercontent.com/102754207/161110452-78851d31-0d57-4bb6-83d9-5577583e4289.png)
![Screen Shot 2022-03-31 at 11 59 27 AM](https://user-images.githubusercontent.com/102754207/161110458-387ee513-5eea-46b3-97dc-1063ed3b7286.png)
![Screen Shot 2022-03-31 at 11 59 43 AM](https://user-images.githubusercontent.com/102754207/161110459-1b493de2-0b97-42b4-ad6d-c632e6d6a65c.png)

**System (please complete the following information):**

Companion 2.1.4
Vicreo 4.0.6
MacOS Big Sur 11.6.4

**Comment by JeffreyDavidsz** [comment]
Hi @mac25rice you would need a newer version of Companion to work. 2.2.0 candidate release or a beta build

**Comment by mac25rice** [comment]
Thank you so much and sorry for the beginners question.

**Comment by JeffreyDavidsz** [comment]
No problem, if you need any help let me know
