### ISSUE TITLE
Vicreo receives data but does nothing with it

### ISSUE THREAD

**Issue by jsnyder886** [bitfocus/companion-module-vicreo-hotkey#51]
**Describe the bug**
I've been using vicreo with companion for months now without problems.  Nothing has changed on my setup except updating to the latest beta of companion.  The listener shows that it receives the commands, but new today, it doesn't seem to do anything with the information when it gets it.  I can run the same key sequences manually on the PCs and they work fine.  So Vicreo receives the commands, Autohotkey does work, but vicreo doesn't send the key strokes to the computer for Autohotkey to process any longer for some reason.

**Version**
I had been on vicreo 2.1.0 on both computers that run a listener.  Through troubleshooting I upgraded one of them to 4.0.8 just to try something/anything.  Same results on both computers regardless of version.  Companion is 2.2.0-4055.  Previous Companion version was 2.2.0-4024.  I downgraded back to that version and vicreo works as expected on the computer that still has 2.1.0 running on it.  It does not work with the computer running 4.0.8 which would be expected as the latest update would be required to connect to version 4.

**Expected behaviour**
Keystrokes to be sent to the computer as expected.

**System (please complete the following information):**
Windows 11

**Comment by JeffreyDavidsz** [comment]
Hi @jsnyder886 since this month older versions of the listener aren't supported anymore. Older Companion versions will still work with VICREO Listener 2.1.0. Newer Companion will only work with version 3 and up. Now the main difference is that there is a license needed when you use pro stuff like password protection and more then single key or combination. The license is a small fee or €50 a year to keep things running. In your case, use the beta and version 4.0.8. That should work, the log might give some extra information, if needed. If you do single or combinations, it stays free. If you need more,then you can acquire a license from the site. If you need any help or assistance just let me know

**Comment by rfergusonmedia** [comment]
Here you go
<img width="401" alt="Screen Shot 2022-04-04 at 2 07 25 PM" src="https://user-images.githubusercontent.com/102980337/161605079-b9785c16-5f4e-4a1c-b62a-4047b79163e7.png">
<img width="395" alt="Screen Shot 2022-04-04 at 2 07 38 PM" src="https://user-images.githubusercontent.com/102980337/161605099-3ae92eaf-eeb7-4d3f-9e00-b072e65e816c.png">

**Comment by JeffreyDavidsz** [comment]
Just to make sure can you delete the button and recreate one? And test it? The screenshot isn't clear to me

**Comment by JeffreyDavidsz** [comment]
Just to be sure, I believe you can still select older versions in 2.2.0. but you should be able to select > 3.0.0 the older listener had a different syntax. You can find it under the instance/connection settings of the listener

**Comment by rfergusonmedia** [comment]
I deleted the button and re-added, I also made sure that companion is pointing to the new listener (> 3.0.0).  The JSON error message is now gone however my Mac still shows the command in the listener log but the machine doesn't process the command.

I also purchased the license just to make sure that I didn't need keypresses beyond the basics on my Mac but still same issue.

**Comment by JeffreyDavidsz** [comment]
Ok i'll look into it. meanwhile can you send me the log output of the command it receives?

**Comment by JeffreyDavidsz** [comment]
Hi @rfergusonmedia I've tested the download of 4.0.8 on mac. Initially I had issues to. It seems OSX has problems with executing task when rights are not correct or certificate is missing. The certificate is there (signing of the app), so must be a rights thing. Under Sys Pref > privacy look at Accessibility. The program should be there checked. remove and re-add the checkbox. Also to a restart of the Listener (in the menu hit Quit not just the red dot). I think that would work for you

**Comment by JeffreyDavidsz** [comment]
Step 1 download and accept
Step 2 Accept System Events
Step 3 It will ask to accept accessibility, so open System Preferences (by clicking on the button)
Step 4 Checkmark the VICREO-Listener
Step 5 Close System Preferences

There can be issues when there is a previous version installed. In the System Preferences uncheck the VICREO-Listener. After thank you would need to restart and do Step 1-5 again. I have seen it before, but I'm not able to reproduce it at this time. Let me know if above works for you, so I can help you to get it working

**Comment by rfergusonmedia** [comment]
The above did work and I'm back up and going.  Thank you so much for your help!!!

**Comment by JeffreyDavidsz** [comment]
Good to hear, I'll update the site with some tips. If you need anything let me know
