### ISSUE TITLE
Send shell command

### ISSUE THREAD

**Issue by Tanis74** [bitfocus/companion-module-vicreo-hotkey#52]
Hi. I am trying to run a program with a listener. I don't understand what syntax to use, 
I tried this 
`start C:\Program Files (x86)\AIMP\AIMP.exe`
and this 
`start "C:\Program Files (x86)\AIMP\AIMP.exe"`
but i get an error

`17:28:52 Error paring JSONSyntaxError: Unexpected token P in JSON at position 35`
`17:27:14 Error paring JSONSyntaxError: Unexpected token C in JSON at position 33`

- Companion Version (2.2.0+3998-ccea40c7)
- VICREO Listener 4.0.12
![image](https://user-images.githubusercontent.com/5111569/164461360-ceb15452-3196-4d85-9ddc-c2401637b3af.png)

**Comment by JeffreyDavidsz** [comment]
On windows you can use both file and shell action and just the path with "". You should upgrade to at least build 4095 of Companion, there was a bug that killed the file action.

**Comment by JeffreyDavidsz** [comment]
![Schermafdruk 2022-04-21 15 16 01](https://user-images.githubusercontent.com/40557816/164466217-4ebfae84-550b-4657-bf2c-68222795cfd9.png)

**Comment by Tanis74** [comment]
it's work!!! Thank you/
