### ISSUE TITLE
Cannot Install Listener, only HotKey

### ISSUE THREAD

**Issue by hparsons56** [bitfocus/companion-module-vicreo-hotkey#53]
**Describe the bug**
I'm not sure if it's a bug, or if I'm doing something wrong, but I've tried both 5.0.0 and 4.0.12, uninstalling and reinstalling each time.

In Companion under Add Connection, I click ADD next to VICREO Listener, and it adds VICREO hotkey. Adding VICREO hotkey adds hotkey, but I cannot add Listener. 

**Version**
Which version of the listener and which version of companion
both 5.0.0 and 4.0.12

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Add Connection (in Companion)
2. Click on VICREO Listener

**Expected behaviour**
Expect to see VICREO Listener

**Screenshots**

![Selecting](https://user-images.githubusercontent.com/22893632/167973418-ca260ce1-b9d5-4cd2-b6d1-8ea0676d86bb.png)
![added](https://user-images.githubusercontent.com/22893632/167973429-e8f4a9e6-701d-4c9f-92d1-754a455b7a4b.png)

**System (please complete the following information):**

- Companion Version 2.2.0+3998-ccea40c7)
- Propresenter 7.9 (118030345)

**Additional context**

**Comment by hparsons56** [comment]
As a followup, this may not even be a problem. Here's the scenario.
Last week, I updated Companion, but found that one of my Vicreo keys stopped working (<ctrl>1). I found this was because I needed to update.
Tonight, I updated, and none of the keys worked. So, I stepped through the setup. That's when I noticed the Hotkey vs Listener issue. Tried all my troubleshooting, installing, uninstalling, and nothing worked. After I posted this as a bug, I went and looked closer, and none of my key entries were there any more. Adding the back made everything work again.
So, I'm thinking the Hotkey vs Listener always was this way, and the odd labeling made me think THAT was the error, rather than the key settings getting lost during the update.

**Comment by JeffreyDavidsz** [comment]
Side note: I noticed on your screenshot that the target IP is empty. It cannot work without an IP address, but it should give an error about that. 
I understand you have it working again?

**Comment by hparsons56** [comment]
Yes. I got it working. I knew it needed an IP address, but did the screen shot to show what got added. I had tried a both loop back and the actual IP address. But the immediate problem was I needed to re-enter my keystrokes.

I do have a question if I may. Is there actually a listener that is different than Hotkey, or do bot "ADD" buttons add the same module?

**Comment by JeffreyDavidsz** [comment]
They add the same module. Originally I started with hotkey. But the program is called listener. So later I added listener, so people can find it more easy
