### ISSUE TITLE
Window App Focus Problem

### ISSUE THREAD

**Issue by Nevadadave** [bitfocus/companion-module-vicreo-hotkey#54]
This maybe a user error, but Iam having a problem I can't figure out.
I can only get applications to receive Hot Keys when their window has focus.
If I press the same Hot Key on a physical keyboard all apps receive the Hot Key regardless of focus status.
Windows 10 21H2  
Bitfocus Companion 2.2.2
Vicreo  5.0.0 (Basic)

**Comment by JeffreyDavidsz** [comment]
Not an error. The listener is a keyboard emulator. The normal behavior should be that the commands only work on the focused screen. There are applications that fetch all keyboard actions. So my guess you have one or more of them running. 
For example when you hit alt+f4 it won't close all your applications, but only the ones that have focus.
Which applications are you running?

**Comment by Nevadadave** [comment]
Thanks So Much! for looking at my problem.

 

More details about my setup

 

2 Screen PC set up

OBS on screen 1,  A browser (Edge) on screen 2 (doing screen capture)

I am not using Elgato Stream Deck hardware.

Companion is running  on a different computer (VIA Web Buttons)

If the browser has focus, OBS will not receive hot keys (Alt 1, Alt 2, Alt 3 …).

Vicreo Listener’s log always shows proper hot key events.

If OBS has focus, OBS always receives hot key presses (VIA Companion).

If I use physical keyboard OBS will receive hot Keys when the browser has focus.

I am using a Logitech wireless mouse and keyboard, have you heard of their driver interfering?

**Comment by JeffreyDavidsz** [comment]
I understand your issue, but there is nothing I can do about that unfortunately. Its the way OBS listens to incoming keys

**Comment by bryce-seifert** [comment]
@Nevadadave You could also try using the OBS module in Companion to control OBS, that should allow you to send actions (or even OBS hotkeys) while it's not in focus

**Comment by Nevadadave** [comment]
I am using the companion module to switch scenes, but I use hot keys to trigger move transitions & and for muting mics.

**Comment by bryce-seifert** [comment]
@Nevadadave I would recommend looking at the Trigger Hotkey by Key action in the OBS module.

**Comment by Nevadadave** [comment]
Thank You , Thank You , Thank You.

 

I was in the process of  programming up a ESP32 to be a web server and a HID keyboard device to press keys on a GET request.
