### ISSUE TITLE
Send KeyPress To MacOS Process (Question)

### ISSUE THREAD

**Issue by tacvideo** [bitfocus/companion-module-vicreo-hotkey#55]
**Question**
For "**Send KeyPress To MacOS Process**", for "**Process Search String**"; does this have to be an exact match or can we use wild cards and/or mixed case?

**Version**
Vicreo: 2.1.0
Companion: (2.2.2+4454-v2-2.2-be663609)

**To Reproduce**
I have it working for "ProPresenter 6", but as I start transitioning to 7, I'm wondering if I can simply change the "**Process Search String**" so it'll work on either version, or if I need to duplicate each action and customize.

**Expected behaviour**
N/A

**Screenshots**
N/A

**System (please complete the following information):**
MacOS 12.4

**Additional context**
N/A

**Comment by JeffreyDavidsz** [comment]
This needs to be an exact match (as far as I know). This is operating system behavior.
