### ISSUE TITLE
VICREO Esc keypress on Mac Giving Error

### ISSUE THREAD

**Issue by npruzaniec** [bitfocus/companion-module-vicreo-hotkey#56]
**Describe the bug**
Using the `VICREO hotkey: special key` action mapped to send `Esc` VICREO Listener shows error:
```Error paring JSONError: Invalid key code specified.```
```received: {"key":"escape","type":"pressSpecial"}```

**Version**
- VICREO Listener 5.0.0 Basic
- VICREO Hotkey Listener plugin for Companion v3.0.3

**To Reproduce**
Set `VICREO hotkey: special key` with "Special key to send" set to `Esc`
Press button - VICREO Listener shows error

**Expected behaviour**
Should trigger keyboard press of Escape key.

**Screenshots**

**System (please complete the following information):**
- Intel MacOS 12.4
- Companion 2.3.0+4548-beta-91f06aba

**Additional context**
Just using Companion with standard Stream Deck setup

**Comment by JeffreyDavidsz** [comment]
Hi thank you for this, I've posted a fix for this. Let me know, if it works for you

**Comment by npruzaniec** [comment]
Amazing. Thanks for the quick response. Will check this out later this week.

**Comment by npruzaniec** [comment]
I don't see the updated release in this git. Should I be looking somewhere else?

**Comment by JeffreyDavidsz** [comment]
vicreo-listener.com

**Comment by npruzaniec** [comment]
Ahh perfect, I thought you meant you updated the integration. Thanks again!

**Comment by npruzaniec** [comment]
Confirmed today this is working for me now. Much appreciated!!
