### ISSUE TITLE
Empty password does not seems to work

### ISSUE THREAD

**Issue by wasabi1809** [bitfocus/companion-module-vicreo-hotkey#59]
**Describe the bug**
Empty password seems to have a hash value sent instead of empty string

**Version**
Companion 2.4.1 
Module V3.0.4

**To Reproduce**
Steps to reproduce the behaviour:

Send an empty password to VICRE Listener 

**Expected behaviour**
an empty string sent "" but get a hash value instead

**System (please complete the following information):**

MacOS Intel
Companion 2.4.1 
Module V3.0.4

**Additional context**

I compiled an old VICREO version 2.0.1 on a RASPBERRY PI, it stopped working after updating to latest stable companion (after a long time), I reckon this is due to the Hash value in the password field (doc says to send empty value to use with older version.

**Comment by JeffreyDavidsz** [comment]
An empty string has a hash value also. The issue is the version of VICREO, you should use a newer version (5). I'm aware that there is no PI version at this moment. At the moment I cannot give a timeframe for that, as the PI version has a lot of conflicts while building.

**Comment by wasabi1809** [comment]
I understand an empty string has a hash value but I saw an example of expected value for older version and the string was empty… will try to find it back and update here…

**Comment by wasabi1809** [comment]
I solved my issue using tcp-udp module instead of the vicreo one.

**Comment by JeffreyDavidsz** [comment]
For this to work a newer version is needed. So no bug
