### ISSUE TITLE
Lauch Application

### ISSUE THREAD

**Issue by SativeMusic** [bitfocus/companion-module-vicreo-hotkey#6]
Hello, 

I would like lauch application on two different mac. I have try with vicreo open file. I think my path is complete, but that don't work.

Path: /Applications/REAPER64.app

An idea?

System: Mac OS 10.13
Vicreo Listener: V1.40
Companion: V1.40

**Comment by Tw0bit** [comment]
I would suggest trying the new v2.0.5 of Vicreo-Listener and the Companion 2.0.0 beta

**Comment by JeffreyDavidsz** [comment]
@SativeMusic yes update it all ;-) use 2.0.5 of the listener. Tested the OSX path yesterday. Update Companion to build 2406 to be sure

**Comment by ondrejvysek** [comment]
I'm having same issue with Companion 2.1.0, Vicreo 2.1.0 both on Windows. 
on the Comanion debug log contains message: 

> instance(internal) : Shell command failed. Guru meditation: {"killed":true,"code":null,"signal":"SIGTERM","cmd":"cmd"} 

and no message logged on the Vicreo side.

**Comment by JeffreyDavidsz** [comment]
If you have no messages logged at all in listener check your settings

**Comment by ondrejvysek** [comment]
I found it works for e.g. notepad without any issues, I'm trying to run VLC remotely C:\Program Files\VideoLAN\VLC\vlc.exe

**Comment by JeffreyDavidsz** [comment]
Seeing your previous post, you are using the internal shell command, not from vicreo....

**Comment by ondrejvysek** [comment]
I'm lost now.

I want to start the VLC on a remote computer (to reload the playlist), I have the following command:

```
VICREO hotkey: Send shell command
with the command: C:\Program Files\VideoLAN\VLC\vlc.exe
```

![image](https://user-images.githubusercontent.com/29834082/96464906-a91a5880-1228-11eb-9545-57b35b96c838.png)

this is not the proper way how/for what to use vicreo?

**Comment by JeffreyDavidsz** [comment]
On the remote computer start a prompt and try it first. What you are doing should be correct and vicreo should receive your command even when it's the wrong one. If it doesn't receive anything like you mentioned before somethings wrong with your settings. My other comment was about your error message, that message does not belong to the module vicreo hotkey

**Comment by ondrejvysek** [comment]
Got it, what I tested:
notepad as a command - worked, notepad app is open
cmd as a command - command received, but cmd not opened 

In meantime, I found a workaround using an internal shell and calling a scheduled task on the remote computer which is working fine.

**Comment by JeffreyDavidsz** [comment]
there's a slide change in reading and using now. Use " around your path (version > 3.0.0)
