### ISSUE TITLE
Asked for Three Key and got a Four Key press

### ISSUE THREAD

**Issue by TomQsTechTips** [bitfocus/companion-module-vicreo-hotkey#61]
**Describe the bug**
Got a little panel for Apple Keynote mostly working with Vicreo Hotkey (including a rotary dial)[Thank you!] with one exception. I created a button to start a slideshow (Command, Option, P). I used the Three key (trio, pro-action) type of instruction and entered "Command, Alt/Option, and P" as the 3 things. In Keynote that should start a slide show What gets executed is Command, Alt/Option, Shift, P (that's FOUR actions) and I can see the cursor change to a Pen. I'm pretty sure I did created the button correctly. 
**Version**
5.0.1 and 2.4.1
**To Reproduce**
Steps to reproduce the behaviour:

1. Go to '...' Described above

**Expected behaviour**
Play Slide Show
**Screenshots**

**System (please complete the following information):**

- Companion Version [e.g. 2.4.1 ]
- vMix version [e.g. v23]

**Additional context**

**Comment by JeffreyDavidsz** [comment]
Do you have a screenshot of your action. And to be sure did you use a capital P, like you typed above or a normal p?

**Comment by JeffreyDavidsz** [comment]
Did you try a normal p?

**Comment by TomQsTechTips** [comment]
No. Just did. It works! Thank you. Is that the normal protocol? Use small letters?

**Comment by JeffreyDavidsz** [comment]
Well without any programming knowledge one could say the when you use a captial letter, the program tries to use a capital letter, so add a shift. This behavior is only on mac tough. 
For a capital letter to be in companion you would have to hold the shift key, right? (or use caps lock) So you as a person are adding stuff when its not needed.
