### ISSUE TITLE
4 Keys Action does not release Ctrl Key after action is triggered

### ISSUE THREAD

**Issue by bigvoxel** [bitfocus/companion-module-vicreo-hotkey#63]
The Ctrl key is not released on Windows 10 after the 4 keys action is triggered.
Companion Version: v2.4.2

Vicreo Version: Tested on: 5.0.1 and 4.0.12 -- both versions have the same issue.
(Currently Vicreo is not licensed)

Setup:
Custom control from Ross Switcher triggers a button in companion that uses Vicreo 4key action.

Have to restart PC to get Ctrl key to release.

**Comment by JeffreyDavidsz** [comment]
Hi @bigvoxel everything other than a single or double keypress should not be working without a license. I'll check why it is pressing down the Ctrl key

**Comment by bigvoxel** [comment]
Thanks for looking into it. I thought it was odd that the 4key was working even though it wasn't licensed.  When you install it, does it automatically give you a trial license?

**Comment by JeffreyDavidsz** [comment]
Found the issue, will be updated in the next release
