### ISSUE TITLE
Combination: comman+F1

### ISSUE THREAD

**Issue by capturahd** [bitfocus/companion-module-vicreo-hotkey#65]
Hello. I'm running two computers at the same time and I want to be able to switch between extended screens, it's mirrored remotely and I can't do command+F1 or add F1 as a special key.

**Comment by JeffreyDavidsz** [comment]
Some functions might be blocked by the os. But first make sure other things work. Can you do a command + tab?
Also show a screenshot of the action you use in companion.

**Comment by JeffreyDavidsz** [comment]
close due no response
