### ISSUE TITLE
Send shell command (pro-action) not working

### ISSUE THREAD

**Issue by brettdicus** [bitfocus/companion-module-vicreo-hotkey#66]
3.00+5776 CompanionPi instance sending commands to Vicreo Listener 5.0.1 Pro with license.

All commands working pro and non-pro except for the Send shell command, not working.

Command that worked in v2 Companion:
./Users/script.sh

Log Output:
23.04.12 15:13:03 Surface/Handler/streamdeck:AL32K2C61475: Button 1.21 pressed
23.04.12 15:13:03 Instance/Wrapper/VICREO_hotkey: Error executing action: s.trim is not a function

**Comment by JeffreyDavidsz** [comment]
65971c7085a0ec79593d0c87b3ff00749878cb1b
Fixes this, thanks for the catch
