### ISSUE TITLE
Not able to send keystroke

### ISSUE THREAD

**Issue by shouweiteoh** [bitfocus/companion-module-vicreo-hotkey#7]
Hi, does this work with High Sierra ? Im on 10.13.6 and not able to send any keystroke.

![Screen Shot 2020-06-22 at 2 22 14 AM](https://user-images.githubusercontent.com/67238979/85232125-4efeb780-b42f-11ea-884b-69af75a7a274.png)

However logs show that they are receiving the command fine, just couldnt emulate keyboard output, appreciate any help.

thanks!

**Comment by JeffreyDavidsz** [comment]
Yes it does but a new version will be released tonight or tomorrow. Check your settings, because for Mac now applescript is used, and you would need to allow that. I'll drop an comment when 2.0.7 is released (it has osx signing). Also update companion if you can. And choose in the instance for the newer version.

**Comment by JeffreyDavidsz** [comment]
<img width="678" alt="Schermafbeelding 2020-06-21 om 16 52 47" src="https://user-images.githubusercontent.com/40557816/85233734-ee5c8400-b408-11ea-85ab-31a3fa5036ea.png">
Its Dutch sorry for that, but you might recognize the icons

**Comment by JeffreyDavidsz** [comment]
2.07 for the Mac is released now

**Comment by shouweiteoh** [comment]
Hi,

I have updated to 2.07

<img width="664" alt="Screen Shot 2020-06-22 at 1 37 54 PM" src="https://user-images.githubusercontent.com/67238979/85252126-a764a200-b48d-11ea-929a-4d9634115b39.png">

Strange, its probably OSX issue but i dont see automation in "privacy" tab.

Weird. Any suggestion?

**Comment by JeffreyDavidsz** [comment]
That's the difference between newer OSX versions. Check the Accessibility tab

**Comment by shouweiteoh** [comment]
I have + it myself on the Accessibility tab. It still doesnt work. weird.

![Screen Shot 2020-06-22 at 9 09 43 PM](https://user-images.githubusercontent.com/67238979/85291199-ccc4d080-b4cc-11ea-98b4-385e82b5d2f8.png)

**Comment by JeffreyDavidsz** [comment]
Did you try to send a string message to a texteditor for example? I see an bug when you use the old syntax on MAC. When you cannot even send a string message, something else is going on.
When you use companion, update to one of the latest and select the newer syntax option in the instance config.

**Comment by shouweiteoh** [comment]
<img width="678" alt="Screen Shot 2020-06-23 at 1 00 52 AM" src="https://user-images.githubusercontent.com/67238979/85315138-145b5480-b4ed-11ea-8444-0704f8e03523.png">
 
Yup string text works. Weird that keystroke doesnt work..... I have been having this issue with octopus listener actually... exact same issue thats why I tried Vicreo and have the same issue...

**Comment by JeffreyDavidsz** [comment]
It looks like a permission thing. The keystroke is with applescript, string message is not. Did you change the setting in Companion to support the new listener?

**Comment by shouweiteoh** [comment]
What setting do I have to change in Companion? I am using v2.0.0

**Comment by JeffreyDavidsz** [comment]
Use a build later than 2406. Then you'll find in where you set the ip the option

**Comment by shouweiteoh** [comment]
perfect!! this solves it for me !! updated to companion 2424 and selected hotkey version >2.0.5 and it works brilliantly !! thank you for your patience !

**Comment by JeffreyDavidsz** [comment]
No problem
