### ISSUE TITLE
Companion V3 converts actions to a single connection wrong connection

### ISSUE THREAD

**Issue by obcocav** [bitfocus/companion-module-vicreo-hotkey#71]
Just noticed as I prep my V3 setup that all my Vicreo actions to 3 different machines/connections were all imported to one single connection which happened to be listed first.  For example I have a button that did the "Open a file" action on 3 different machines.  That button now has the action going to the same machine/connection 3 times.

**Comment by JeffreyDavidsz** [comment]
@Julusian is this something that could be linked more modules (that have no upgrade script), or is this something I missed in this module?

**Comment by Julusian** [comment]
this sounds much more likely for this to be a bug in companion rather than the module.
it shouldnt be possible for a module to mangle the instance id an action is targetting, and even if it did it wouldnt know what other id it should use.

could you provide an export I can use to reproduce this?

**Comment by obcocav** [comment]
@Julusian.  Sorry for the delayed reply.  It is attached. (PDF ext added)
[CompanionServerNEW_custom-config_20230621-1936.companionconfig.pdf](https://github.com/bitfocus/companion-module-vicreo-hotkey/files/11951131/CompanionServerNEW_custom-config_20230621-1936.companionconfig.pdf)
