### ISSUE TITLE
Mouse Click action does not work

### ISSUE THREAD

**Issue by Ajonymous** [bitfocus/companion-module-vicreo-hotkey#73]
**Describe the bug**
Error message received in listener when trying to use the Click the Mouse action and the mouse is not clicked.
```
0:25:43 Error paring JSONTypeError: virtualkeycode.mouseClickLeft is not a function
0:25:43 received: {"type":"mouseClick","button":"left","double":"false","password":"XXXXXXX"}

```
**Version**
Listener 5.2.8
Companion V3.0.0 5927 Beta

**To Reproduce**
Add click mouse action to a button
Once pressed observe the listener log

**Comment by JeffreyDavidsz** [comment]
Hi this issue is being addressed in the 5.3.3 release
