### ISSUE TITLE
1 of 4 computers will not connect via companion

### ISSUE THREAD

**Issue by franklyray** [bitfocus/companion-module-vicreo-hotkey#78]
I have 4 computers on my system. 

I use Companion to control them with Vicreo-listener. 

COMP2 has v5.0 Pro but will not connect in the Connections panel. 

What are my troubleshooting steps?

![VICREO-Listner Companion screen COMP2 issue](https://github.com/bitfocus/companion-module-vicreo-hotkey/assets/4950599/3cccc2f1-9373-4f9f-938c-af7d0d52d794)

![image](https://github.com/bitfocus/companion-module-vicreo-hotkey/assets/4950599/ee82bf3a-1c0f-4cc9-bdcb-74faabd3cede)

**Comment by JeffreyDavidsz** [comment]
Most cases it’s a network issue;
Try a different port 10002 for example 
Disable enable the instance in companion 
Make sure you can ping the 192.168.50.28 machine from the companion machine.
Let me know if it works!

**Comment by franklyray** [comment]
Thanks Jeffrey,

I had COMP2 on the Public Network, changed to private, and the rest of
everything.

Now able to have full use.

Happy Holidays and Prosperous and Healthy New Year. You have always been
very supportive.

**Comment by JeffreyDavidsz** [comment]
Great to hear! Have a wonderful Christmas and a happy new year!
