### ISSUE TITLE
Import Companion Configuration File

### ISSUE THREAD

**Issue by garysteele777** [bitfocus/companion-module-vicreo-hotkey#79]
I am on a windows computer. Is there a way that I can open an ableton file and also import a new configuration file into the Stream Deck companion at the same time? Do I need the Pro version to do this?

Great software. Thanks for your help.

Gary Steele

**Comment by JeffreyDavidsz** [comment]
Opening files and shell commands are more advanced features. Therefor you would need a license. Importing a configuration file into companion is - as far as I know - not possible. So for Abelton, you be ok. But what would you like to do in Companion (with regards to the configuration file)?

**Comment by garysteele777** [comment]
I have a different configuration file in companion for each ableton file
that I open. I wanted to import a new config file into companion when I
open the new ableton file. Probably this can't be done.

Thanks
Gary

**Comment by JeffreyDavidsz** [comment]
For companion; maybe you can do something with variables to change the buttons and or pages? You could setup multiple pages also and while opening a config of abelton, do a goto page action to co to the right page in companion?

**Comment by garysteele777** [comment]
Thanks, I'll check it out.
