### ISSUE TITLE
print screen

### ISSUE THREAD

**Issue by Adele6666** [bitfocus/companion-module-vicreo-hotkey#8]
Hi, 

Vicreo hotkey does not support the special key for print screen??

I am trying to set up command/windows PRT SCR in companion with use of VICREO HOTKEY 
so I was wondering if it was at all possible.

I realize that it is possible to do printscreen for one pc using streamdeck, but I need to use it on 50 PC's simultaneously by companion over IP.

If it is not possible, I have to look for a work around sollution.

Kind Regards
V

**Comment by JeffreyDavidsz** [comment]
Hi @Adele6666 did you try a combination, first command/win and as separate command: printscreen ? I believe that should work already

**Comment by JeffreyDavidsz** [comment]
Closing because of no reply
