### ISSUE TITLE
"Open a file" Preset Not Working

### ISSUE THREAD

**Issue by thespica93** [bitfocus/companion-module-vicreo-hotkey#82]
**Describe the bug**
Trying to use the "One a file" preset and it does not work on Mac.

The end goal is to use the open a file command to bring a window into focus every time I press a button on my stream deck.

**Version**
8.0.6

**To Reproduce**
Steps to reproduce the behaviour:
Loaded the "Open Notepad" preset to my stream deck. Pressing the button does nothing. Confirmed filename path in OSX

**Expected behaviour**
Pressing the button should open the noopad app, or bring the window into focus for keypresses

**Screenshots**
<img width="1179" alt="Screenshot 2024-04-10 at 4 11 28 PM" src="https://github.com/bitfocus/companion-module-vicreo
-hotkey/assets/42631192/422ad74e-76af-4232-b624-26c6c40699d8">

<img width="1148" alt="Screenshot 2024-04-10 at 4 12 10 PM" src="https://github.com/bitfocus/companion-module-vicreo-hotkey/assets/42631192/1d33c742-2e4e-4109-8a11-449348593f7e">

**System (please complete the following information):**
-iMac Apple M1 Sonoma 14.0
- Companion Version 3.2.2

**Comment by JeffreyDavidsz** [comment]
Closing this due to no response, tested locally and works
