### ISSUE TITLE
Zoom Meeting 3-Key Combination

### ISSUE THREAD

**Issue by DavidTNguyen** [bitfocus/companion-module-vicreo-hotkey#9]
It seemed Vicreo on Companion currently only allowed combination of two keys.  It doesn't allow 3 key combination like those Zoom required to control a meeting.  For example, I don't know how to set a button to accept Command+Shift+A to mute/unmute my mic during a Zoom meeting.

<img width="1141" alt="Screen Shot 2021-01-29 at 11 20 39 AM" src="https://user-images.githubusercontent.com/11265859/106306792-23914600-6224-11eb-98e0-dfab99c36241.png">

![Screen Shot 2021-01-29 at 11 18 48 AM](https://user-images.githubusercontent.com/11265859/106306793-2429dc80-6224-11eb-8c0e-f59c82ab87a1.png)

**Comment by JeffreyDavidsz** [comment]
Did you try the trio option?

**Comment by DavidTNguyen** [comment]
@JeffreyDavidsz - trio works!
