### ISSUE TITLE
Error parsing JSON with change mouse position + click the mouse

### ISSUE THREAD

**Issue by Safety13** [bitfocus/companion-module-vicreo-hotkey#91]
**Describe the bug**
When I use companion for my streamdeck and add a button to Open a program, move the mouse at X and Y position and click. The move position not work and make an error. If I disable the click button that work.

I use:
Beta version of Companion 3.5.0 and Listener 8,2.4 Pro

1. Open Companion GUI add a button
2. Make the button open a file
3. Add a second action for the button to move the mouse in an X and Y position you want
4. Add a third action for click mouse button
5. Execute the action in the streamdeck or Test button(same result)
6. See the action not perform correctly
7. Parsing JSON error in Listener

The full error JSON
Error parsing JSON: SyntaxError: Unexpected non-whitespace character after JSON at position 114 (line 1 column 115)

**Screenshots**
![image](https://github.com/user-attachments/assets/d16235f8-e9f7-41a9-84f2-f3c97c92d02b)

**Comment by JeffreyDavidsz** [comment]
Did you put any delay between the actions? If not try 1000ms between each action. If that works lower the delay my first guess is that companion is sending to fast to handle

**Comment by JeffreyDavidsz** [comment]
fixed this in 9.3.0
