### ISSUE TITLE
Long automation steps fire over the top of each other

### ISSUE THREAD

**Issue by calwalker1** [bitfocus/companion-module-vicreo-hotkey#96]
**Describe the bug**
When building a long sequence of VICREO automations using Companion, it seems that you can fire multiple Vicreo commands over the top of each-other. The VICREO listener (9.1.0 pro) seems to handle these incoming poorly if they are too close together (or companion is sending out malformed requests). VICREO in the logs will produce and error when sending an enter command too soon after a Send stringmessage of: `Error parsing JSON: SyntaxError: Unexpected non-whitespace character after JSON at position 83 (line 1 column 84)`

**Version**
VICREO listener 9.1.0 Pro for windows
Companion 3.4.3 (hosted on same computer, connecting via 127.0.0.1

**To Reproduce**
Add a sequence of Vicreo commands in companion, each with a delay that is +100ms of the previous, see attached screenshot.
![Image](https://github.com/user-attachments/assets/fd05512d-5961-48f7-9640-b36063edcafa)

Run button with the VICREO client open to monitor. 
Observe VICREO is producing errors and the keys are not correctly running in sequence (the ENTER) is not passing through.

![Image](https://github.com/user-attachments/assets/c33c9110-5072-490e-9c19-1065d858b718)

Adjust delays so each step is now +1,000ms delay of the previous. Observe VICREO is able to successfully run all commands in sequence.

**Expected behaviour**
When commands are too close, VICREO or the companion module queues the commands until they can be processed.

**System (please complete the following information):**
**Version**
VICREO listener 9.1.0 Pro for windows
Companion 3.4.3 (hosted on same computer, connecting via 127.0.0.1

**Additional context**
I am not stressed that the screenshots include the hashed password. It was mainly set to prevent tampering.

**Comment by JeffreyDavidsz** [comment]
Hi @calwalker1 this is a know problem, Companion is sending the commands over TCP in a stream. That can be in conflict when receiving. I'm working of using REST for this. One tip on the Companion side; use relative delays. Then you don't need to calculate delays yourself. I see you are using msg, this action uses pauzes in between letters, I'll take a look at that.

**Comment by calwalker1** [comment]
Hi thanks for the update! So essentially it's a known bug that's being worked on? And the current workaround is to just increase the delays.
And if I want to send a string of characters is there something better than send-message?

**Comment by JeffreyDavidsz** [comment]
I've finally fixed the bug, please use version 9.3.0 (or up) and test it for you.
The string of characters is made for windows, like if you are typing so there is a bit of delay build in. What would you need? And could you put that in a new issue?

**Comment by calwalker1** [comment]
Hi I don't fully understand what you are saying. I will have a look at the new version and see how the issue behaves.

"The string of characters is made for windows, like if you are typing so there is a bit of delay build in. What would you need? And could you put that in a new issue?"
What does this mean? I am trying to send the following behaviour

```
Send Combo: {CTRL} + L
Type Text: "Video"
Send Enter key
Send Combo: {CTRL} + R
Type text: "(vid) "
```

This is to control disguise media server on a remote server, the shortcut essentially simulates a programmer pressing CTRL - L which brings up the New Layer window. You then search for the layer type "Video" by typing it and pressing ENTER. You then press CTRL - R to bring up the rename window and type "(Vid) " and then via a normal keyboard you type whatever you want (e.g. 'opening logo')
So that condenses the steps to add a new layer to the timeline that is a video type and gets the name ready for you .

**Comment by calwalker1** [comment]
Hi I can confirm this new version seems to work. Many thanks!

**Comment by JeffreyDavidsz** [comment]
"The string of characters is made for windows, like if you are typing so there is a bit of delay build in. What would you need? And could you put that in a new issue?"
What does this mean?

The action is build so that on the receiving machine it looks like someone is actually typing (a bit delay between the letters to appear).
When you have a new item/issue please create a new issue on Github to keep it separated. Thanks
