### ISSUE TITLE
After upgrade to 9.1.0: Error parsing JSON: SyntaxError: Unexpected non-whitespace character after JSON at position 102

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-vicreo-hotkey#98]
**Describe the bug**
After updating to the latest version, commands sending combinations of keyboard shortcuts stopped working, see Fig. An error message appears in the log:

`Error parsing JSON: SyntaxError: Unexpected non-whitespace character after JSON at position 102`

**Version**
9.1.0

**Screenshots To Reproduce**
Take a look at imgs. When I press this button
![Image](https://github.com/user-attachments/assets/7ff9c0ec-59e4-4cd6-af53-9b4594f184a3)
I get these errors:
![Image](https://github.com/user-attachments/assets/207800b7-5817-40d2-bbc0-30c58ea4febe)

I am 100% sure that everything was working correctly and without errors before the upgrade to 9.1.0

**Expected behaviour**
To make it work like before and send the required hotkeys.

**System**
- Companion Version: 3.4.3
- Win10
- Chrome last version
- OBS Studio last version

**Comment by JeffreyDavidsz** [comment]
Just to check when you have 2 actions with delay on the second one, is the issue there?
It seems you have more then 2 actions programmed, did you select relative delay in companion?
If so, try to set it like it's not relative. Could be an issue whit companion also. Let me know!

**Comment by Suenee** [comment]
Yes, the second action after the delay does it. When I temporarily turned it off, it stopped throwing the error.

I extended the delay from 500ms to 1000ms and the error disappeared. I assume that he will want to debug it somehow, because before it worked for you even for a shorter interval (500 ms).

**Comment by Suenee** [comment]
After updating Vicreo to 9.2.0 is errror still there. See images!

![Image](https://github.com/user-attachments/assets/9b61586e-8260-4425-a49d-087cd655e4cd)

![Image](https://github.com/user-attachments/assets/3f57d079-34bc-402e-9bb9-6cb46a47db3c)

The error occurs even if there is a gap of 1 second between the two commands. Personally, I find this quite unfortunate, as less than 500 milliseconds was enough in version below 9.1.0.

**Comment by JeffreyDavidsz** [comment]
I believe I've added a fix for this now (version 9.3.0 which will autoupdate). You can send the delay to 500ms first, should work. Then try 10ms. Depending of handling the action a delay of 0ms should also work now. I've tested this on MAC with a mouse position and right after a left click
